document.write('<div class="modal fade" id="loginModal" role="dialog" aria-labelledby="myModalLabel">'
    +'<div class="modal-dialog" role="document">'
    +'<div class="modal-content">'
    +'<div class="modal-body">'
    +'<span class="title">登录</span>'
    +'<form method="post" class="loginForm">'
    +'<input type="text" name="userName" class="userName form-control" placeholder="用户名/邮箱/手机号">'
    +'<input type="password" name="psword" class="psword form-control" placeholder="密码">'
    +'<a class="register" data-toggle="modal" data-target="#registerModal">注册</a>'
    +'<a href="#">忘记密码</a>'
    +'<button type="submit" class="button button-primary button-rounded button-small">登录</button>'
    +'</form>'
    +'</div>'
    +'</div>'
    +'</div>'
    +'</div>'
    +'<div class="modal fade" id="registerModal" role="dialog" aria-labelledby="myModalLabel">'
    +'<div class="modal-dialog" role="document">'
    +'<div class="modal-content">'
    +'<div class="modal-body">'
    +'<span class="title">注册</span>'
    +'<form method="post" class="loginForm">'
    +'<input type="text" name="userName" class="userName form-control" placeholder="用户名/邮箱/手机号">'
    +'<input type="password" name="psword" class="psword form-control" placeholder="密码">'
    +'<a class="login" data-toggle="modal" data-target="#loginModal">已有账号,去登录</a>'
+'<button type="submit" class="button button-primary button-rounded button-small">注册</button>'
    +'</form>'
    +'</div>'
    +'</div>'
    +'</div>'
    +'</div>'
    +'<script>'
    +'$(document).ready(function(){'
//            $(".userBox a").click(function(){
//                $("body").css({
//                    'padding-right':'-17px'
//                })
//            });
        +'$(".modal-content .login").click(function(){'
           +' $(".modal-backdrop").hide(10);'
            +'$("#registerModal").hide(10);'
        +'});'
        +'$(".modal-content .register").click(function(){'
            +'$(".modal-backdrop").hide(10);'
            +'$("#loginModal").hide(10);'
        +'});'
    +'})'
    +'</script>'
)